branches:
  only:
  - master
  - "/^v.*$/"
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
matrix:
  include:
  - os: linux
    python: 3.4
  - os: linux
    python: 2.7
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - brew install python2
      - pip install virtualenv
      - python2 -m virtualenv env
      - source env/bin/activate
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - python3 -m venv env
      - source env/bin/activate
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- pip install -e .
- parserator train training/labeled.xml usaddress
script:
- nosetests --with-coverage --cover-package=usaddress
deploy:
  - provider: pypi
    skip_cleanup: true
    user: datamade.wheelbuilder
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    distributions: "sdist bdist_wheel"
    password: $PYPIPASSWORD
env:
  global:
  - secure: BltVbgXfZWBFpZId6l33MfMY+O9k6O75bJsyEqz+8OQ8Y7wF2NH85er+8z/gClPjbbE1UDBh+1m4ifUM+QEp6YvgLaciT2bd7x+4Z/Ur5s3IXb1dJML1W/IdBUiN8VMeDSBzHk/LxOCDnPvEPG4wRYxEK0Be+1d70An0r43MriM=
